include ../../latex.Makefile


all: lab5-prelab.pdf
lab5-prelab.pdf: lab5-prelab.tex lab5-frontpage.pdf lab5-bode.png lab5-lag-bode.png lab5-lag-step.png lab5-lead-bode.png lab5-lead-step.png

clean:
	rm -f lab5-prelab.pdf
