include ../../c.Makefile


all: alphabetic.o array.o avgmoney.o contains.o dateSplit.o day.o event.o factor.o fraction.o hello.o histogram.o poly.o reduce.o reverse.o rpsls.o sf.o sudoku.o twin.o

clean:
	rm -f *.o
