VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty32"
  config.vm.provision :shell, path: "bootstrap.sh"
  config.vm.network :forwarded_port, host:4567, guest:8000

  config.ssh.forward_agent = true

  config.vm.synced_folder "distribute", "/home/vagrant/distribute"
end
